on: push
jobs: 
  first-job:
    runs-on: ubuntu-latest
    container: node:17.6.0
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v3
      - run: node app.js
